version = 1

[[annotations]]
path = "images/*"
SPDX-FileCopyrightText = "2025 aesc silicon"
SPDX-License-Identifier = "CERN-OHL-W-2.0"

[[annotations]]
path = "project/*"
SPDX-FileCopyrightText = "2025 aesc silicon"
SPDX-License-Identifier = "CERN-OHL-W-2.0"

[[annotations]]
path = ".scalafmt.conf"
SPDX-FileCopyrightText = "2025 aesc silicon"
SPDX-License-Identifier = "CERN-OHL-W-2.0"
